features/customer-reviews
54Cat/ice-test pull request #4
Opened 2022-05-08 08:29 UTC by HavryshDmytro

add section customer-reviews

2022-05-09 12:43 UTC, 54Cat commented on src/sass/components/_customer-reviews.scss
> +.customer-reviews__text {
пока оставляем как есть, либо сами подумаем, либо уже ментор исправит

2022-05-09 18:51 UTC, HavryshDmytro commented on src/sass/components/_customer-reviews.scss
> +.customer-reviews__text {
+

2022-05-09 18:51 UTC, HavryshDmytro commented on src/sass/components/_customer-reviews.scss
> +    position: relative;
+

2022-05-09 18:51 UTC, HavryshDmytro commented on src/sass/utils/_variables.scss
> +  --customer-reviews-bg: #fafafa;
+

2022-05-09 18:51 UTC, HavryshDmytro commented on src/sass/main.scss
> -
ok

2022-05-10 09:42 UTC, 54Cat requested changes
в проекте всего один спрайт с свг
отправь мне свг, я бістренько добавлю их, а из своей папки удали

2022-05-10 09:42 UTC, 54Cat commented on src/partials/header.html
> +  <div class="container navigation">
почему здесь есть изменения, это же не твоя секция
если что-то заметил пиши в личку

2022-05-10 17:07 UTC, merged