About(How it is made) section
54Cat/ice-test pull request #5
Opened 2022-05-08 10:10 UTC by VolodymyrBashtanyuk

Section About(How it is made) completed. Please review.

2022-05-08 17:51 UTC, Rechkalov1 reviewed
Вроди все гуд

2022-05-09 09:44 UTC, 54Cat requested changes
прошу внести изменения
не забывай обновить локальный репозиторий

2022-05-09 09:44 UTC, 54Cat commented on src/sass/components/_about.scss
> +}
размер текста в каждом типо екрана разный, добавть

2022-05-09 09:44 UTC, 54Cat commented on src/sass/components/_about.scss
> +.about__subtitle {
переимуйте класс, а то subtitle это подзаголовок, а у вас над заголовком текст
не забудьте переимовать в html файле

2022-05-09 09:44 UTC, 54Cat commented on src/partials/about.html
> +            <p class="about__subtitle">tradition and love</p>
переимуйте класс, а то subtitle это подзаголовок, а у вас над заголовком текст

2022-05-09 09:44 UTC, 54Cat commented on src/sass/components/_about.scss
> +    margin-bottom: 80px;
исправте отступ согласно макета

2022-05-09 09:44 UTC, 54Cat commented on src/sass/components/_about.scss
> +    }
добавте отступ для десктопа

2022-05-09 09:44 UTC, 54Cat commented on src/sass/components/_about.scss
> +    font-style: normal;
эта строчка не нужна

2022-05-09 17:49 UTC, 54Cat requested changes
внесите изменения

2022-05-09 17:49 UTC, 54Cat commented on src/sass/components/_about.scss
> +.about__subtitle {
не вижу никаких изменений

2022-05-09 17:49 UTC, 54Cat commented on src/sass/components/_about.scss
> +}
не вижу медиа правил

2022-05-09 17:49 UTC, 54Cat commented on src/sass/components/_about.scss
> +    margin-bottom: 80px;
в макете для таблета отступ 40px

2022-05-09 17:49 UTC, 54Cat commented on src/sass/components/_about.scss
> +    }
не вижу правила для десктопа

2022-05-09 17:49 UTC, 54Cat commented on src/sass/components/_about.scss
> +    font-style: normal;
удалите   font-style: normal;

2022-05-10 05:25 UTC, VolodymyrBashtanyuk commented
done

2022-05-10 09:19 UTC, 54Cat requested changes
проверьте отстут от тайтла до следующего контента
не забудьте обновить локальную ветку

2022-05-10 09:19 UTC, 54Cat commented on src/partials/about.html
> +            <p class="about__lable">tradition and love</p>
переименуй класс на .uppertitle

2022-05-10 09:19 UTC, 54Cat commented on src/partials/about.html
> +            <h2 class="about__title">how it’s made?</h2>
переименуй класс на .title

2022-05-10 09:19 UTC, 54Cat commented on src/sass/components/_about.scss
> +.about__lable {
удалите этот класс

2022-05-10 09:19 UTC, 54Cat commented on src/sass/components/_about.scss
> +.about__title {
и этот класс тоже удалите

2022-05-10 11:46 UTC, VolodymyrBashtanyuk commented
done

2022-05-10 11:53 UTC, 54Cat approved these changes

2022-05-10 11:53 UTC, merged